### PR TITLE
Added main page animation

### PR DESCRIPTION
**Pull request by dhairyabaweja**
# Description

Added main page animation.

Fixes #15 

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

### CODE REVIEW

**Comment by Tlazypanda** [comment]
@dhairyabaweja Hey can you please change the pr template according to the changes made by you 😅 Also provide a live link 😄 Also resolve the merge conflicts

**Comment by dhairyabaweja** [comment]
https://dhairyabaweja.github.io/GirlsDoCode/

**Comment by pradeepgangwar** [comment]
Looks good. Can be merged for now. Later on we can improve it further.

**Comment by pradeepgangwar** [comment]
@Tlazypanda Which issue this PR solves? Also i guess the issue was assigned to someone else if the issue us #9

**Comment by Tlazypanda** [comment]
@pradeepgangwar This fixes #15 so we can proceed with merging and further improve on it.

**Pull request merged**
